
// Siglas e Significados
// QAG: Qualidade da Água Superficial
// QSD: Qualidade de Sedimentos
// PMM: Monitoramento Meteorológico e Oceanográfico
// RSA: Ruído Subaquático
// QAR: Qualidade do Ar
// QEF: Qualidade de Efluentes Líquidos


export type QAGResultadosRow = {
    [coluna: string]: string;
};

export const expectedColumnsQAG = [
    "Data",
    "Ponto",
    "Classe",
    "pH (N/A)",
    "OD (mg/L O2)",
    "Profundidade",
    "2,4-D (μg/L)",
    "Benzeno (mg/L)",
    "Endrin (μg/L)",
    "Gution (μg/L)",
    "Turbidez (UNT)",
    "Xileno (μg/L)",
    "2,4,5-T (μg/L)",
    "Criseno (μg/L)",
    "Estireno (mg/L)",
    "Tolueno (μg/L)",
    "Óleos e graxas",
    "2,4,5-TP (μg/L)",
    "Alacloro (μg/L)",
    "Atrazina (μg/L)",
    "Carbaril (μg/L)",
    "Malation (μg/L)",
    "Nitrato (mg/L N)",
    "Nitrito (mg/L N)",
    "Tipo de análise",
    "Toxafeno (μg/L)",
    "Benzidina (μg/L)",
    "Acrilamida (μg/L)",
    "Boro total (mg/L B)",
    "Clorofila a (μg/L)",
    "Etilbenzeno (μg/L)",
    "Metoxicloro (μg/L)",
    "2-Clorofenol (μg/L)",
    "Antimônio (mg/L Sb)",
    "Diclorometano (mg/L)",
    "Materiais flutuantes",
    "Tricloroeteno (mg/L)",
    "Trifluralina (μg/L)",
    "Cromo total (mg/L Cr)",
    "Fenóis totais (mg/L)",
    "Polifosfatos (mg/L P)",
    "Prata total (mg/L Ag)",
    "Zinco total (mg/L Zn)",
    "Bário total (mg/L Ba)",
    "Chumbo total (mg/L Pb)",
    "Lítio total (mg/L Li)",
    "Tetracloroeteno (mg/L)",
    "Triclorobenzeno (mg/L)",
    "Tálio total (mg/L Tl)",
    "Urânio total (mg/L U)",
    "1,1-Dicloroeteno (mg/L)",
    "1,2-Dicloroetano (mg/L)",
    "Cianeto livre (mg/L CN)",
    "Cloreto total (mg/L Cl)",
    "Cobalto total (mg/L Co)",
    "Cádmio total (mg/L Cd)",
    "Fluoreto total (mg/L F)",
    "Fósforo Total (mg/L P)",
    "Lindano (g-HCH) (μg/L)",
    "Níquel total (mg/L Ni)",
    "Pentaclorofenol (μg/L)",
    "Tributilestanho (μg/L)",
    "Vanádio total (mg/L V)",
    "2,4-Diclorofenol (μg/L)",
    "Arsênio total (mg/L As)",
    "Benzo (a) pireno (μg/L)",
    "Berílio total (mg/L Be)",
    "Cor verdadeira (mg Pt/L)",
    "Monoclorobenzeno (μg/L)",
    "Selênio total (mg/L Se)",
    "Sulfato total (mg/L SO4)",
    "Aldrin + Dieldrin (μg/L)",
    "Manganês total (mg/L Mn)",
    "Mercúrio total (mg/L Hg)",
    "Cobre dissolvido (mg/L Cu)",
    "Ferro dissolvido (mg/L Fe)",
    "Benzo (a) antraceno (μg/L)",
    "2,4,6 - Triclorofenol (mg/L)",
    "Benzo(b) fluoranteno (μg/L)",
    "Benzo(k) fluoranteno (μg/L)",
    "DBO 5 dias a 20°C (mg/L O2)",
    "Alumínio dissolvido (mg/L Al)",
    "Clordano (cis + trans) (μg/L)",
    "Cloro residual total (mg/L Cl)",
    "Resíduos sólidos objetáveis",
    "Tetracloreto de carbono (mg/L)",
    "Dibenzo (a,h) antraceno (μg/L)",
    "2 , 4 , 6 - Triclorofenol (mg/L)",
    "Carbono orgânico total (mg/L C)",
    "Sólidos dissolvidos totais (mg/L)",
    "Dodecacloro pentaciclodecano (μg/L)",
    "Nitrogênio amoniacal total (mg/L N)",
    "Densidade de cianobactérias (cel/mL)",
    "Endossulfan (a + b + sulfato) (μg/L)",
    "PCBs - Bifenilas Policloradas (μg/L)",
    "Coliformes termotolerantes (NMP/100mL)",
    "Sulfeto (H2S não dissociado) (mg/L S)",
    "Demeton (Demeton-O + Demeton-S) (μg/L)",
    "Sulfetos (H2S não dissociado) (mg/L S)",
    "Heptacloro epóxido + Heptacloro (μg/L)",
    "Substâncias que comuniquem gosto ou odor",
    "Fósforo total (ambiente lótico) (mg/L P)",
    "Corantes provenientes de fontes antrópicas",
    "Fósforo total (ambiente lêntico) (mg/L P)",
    "DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) (μg/L)",
    "Sulfetos (como H2S não dissociado) (mg/L S)",
    "Nitrogênio amoniacal total (pH > 8,5) (mg/L N)",
    "Fósforo total (ambiente intermediário) (mg/L P)",
    "Nitrogênio amoniacal total (pH ≤ 7,5) (mg/L N)",
    "Nitrogênio amoniacal total (7,5 < pH ≤ 8,0) (mg/L N)",
    "Nitrogênio amoniacal total (8,0 < pH ≤ 8,5) (mg/L N)",
    "Substâncias que produzem odor e turbidez (Virtualmente ausentes)",
    "Substâncias tensoativas que reagem com o azul de metileno (mg/L LAS)",
    "Substâncias que produzem cor, odor e turbidez (Virtualmente ausentes)"
];
export const expectedColumnsQAGS = [
    "ponto",
    "data",
    "coordenada_x",
    "coordenada_y",
    "usos_preponderantes_da_agua",
    "tipo_de_analise",
    "aluminio_mg_l",
    "antimonio_mg_l",
    "arsenio_mg_l",
    "bario_mg_l",
    "berilio_mg_l",
    "boro_mg_l",
    "cadmio_mg_l",
    "chumbo_mg_l",
    "cianeto_mg_l",
    "cloreto_mg_l",
    "cobalto_mg_l",
    "cobre_mg_l",
    "cromio_cr_iii_cr_vi_mg_l",
    "ferro_mg_l",
    "fluoreto_mg_l",
    "litio_mg_l",
    "manganes_mg_l",
    "mercurio_mg_l",
    "molibdenio_mg_l",
    "niquel_mg_l",
    "nitrato_expresso_em_n_mg_l_n",
    "nitrito_expresso_em_n_mg_l_n",
    "prata_mg_l",
    "selenio_mg_l",
    "sodio_mg_l",
    "solidos_totais_dissolvidos_std_mg_l",
    "sulfato_mg_l",
    "uranio_mg_l",
    "vanadio_mg_l",
    "zinco_mg_l",
    "acrilamida_ug_l",
    "benzeno_ug_l",
    "benzo_antraceno_ug_l",
    "benzo_fluoranteno_ug_l",
    "benzo_k_fluoranteno_ug_l",
    "benzo_pireno_ug_l",
    "cloreto_de_vinila_ug_l",
    "cloroformio_ug_l",
    "criseno_ug_l",
    "1_2_diclorobenzeno_ug_l",
    "1_4_diclorobenzeno_ug_l",
    "1_2_dicloroetano_ug_l",
    "1_1_dicloroeteno_cis_trans_ug_l",
    "1_2_dicloroeteno_trans_156_60_5_ug_l",
    "dibenzo_antraceno_ug_l",
    "diclorometano_ug_l",
    "estireno_ug_l",
    "etilbenzeno_ug_l",
    "fenois_mg_l",
    "indeno_1_2_3_pireno_ug_l",
    "pcbs_somatoria_de_7_ug_l",
    "tetracloreto_de_carbono_ug_l",
    "triclorobenzenos_1_2_4_tcb_1_3_5_tcb_1_2_3_ug_l",
    "tetracloroeteno_ug_l",
    "1_1_2_tricloroeteno_ug_l",
    "tolueno_ug_l",
    "xileno_total_o_m_p_ug_l",
    "alaclor_ug_l",
    "aldicarb_ald_sulfona_ald_sulfoxido_ug_l",
    "aldrin_dieldrin_ug_l",
    "atrazina_ug_l",
    "bentazona_ug_l",
    "carbofuran_ug_l",
    "clordano_cis_trans_ug_l",
    "clorotalonil_ug_l",
    "clorpirifos_2_4_d_ug_l",
    "ddt_p_p_ddt_p_p_dde_p_p_ddd_ug_l",
    "endosulfan_i_ii_sulfato_ug_l",
    "endrin_ug_l",
    "glifosato_ampa_ug_l",
    "heptacloro_epoxido_1024_57_3_ug_l",
    "hexaclorobenzeno_ug_l",
    "lindano_gama_bhc_ug_l",
    "malation_ug_l",
    "metolacloro_ug_l",
    "metoxicloro_ug_l",
    "molinato_ug_l",
    "pendimetalina_ug_l",
    "pentaclorofenol_ug_l",
    "permetrina_ug_l",
    "propanil_ug_l",
    "simazina_ug_l",
    "trifuralina_ug_l",
    "e_coli_nmp_100_ml",
    "enterococos_nmp_100_ml",
    "coliformes_termotolerantes_nmp_100_ml",
]


export type QualidadeSedimentosRow = {
    [coluna: string]: string;
};

export const expectedColumnsQDS = [
    "Ponto",
    "Classe",
    "Tipo de análise",
    "Areia muito grossa (%)",
    "Areia grossa (%)",
    "Areia média (%)",
    "Areia fina (%)",
    "Areia muito fina (%)",
    "Silte (%)",
    "Argila (%)",
    "Carbonato (%)",
    "MO (%)",
    "Carbono Orgânico Total (%)",
    "Nitrogênio Kjeldahl Total (mg/kg)",
    "Fósforo Total (mg/kg)",
    "Arsênio (mg/kg)",
    "Cadmio (mg/kg)",
    "Chumbo (mg/kg)",
    "Cobre (mg/kg)",
    "Cromo (mg/kg)",
    "Mercúrio (mg/kg)",
    "Níquel (mg/kg)",
    "Zinco (mg/kg)",
    "Tributilestanho (μg/kg)",
    "HCH (Alfa HCH) (μg/kg)",
    "HCH (Beta HCH) (μg/kg)",
    "HCH (Delta HCH) (μg/kg)",
    "HCH (Gama HCH/lindano) (μg/kg)",
    "Clordano (Alfa) (μg/kg)",
    "Clordano (Gama) (μg/kg)",
    "DDD (μg/kg)",
    "DDE (μg/kg)",
    "DDT (μg/kg)",
    "Dieldrin (μg/kg)",
    "Endrin (μg/kg)",
    "Bifenilas Policloradas  (μg/kg)",
    "Benzo(a)antraceno (μg/kg)",
    "Benzo(a)pireno (μg/kg)",
    "Criseno (μg/kg)",
    "Dibenzo(a,h)antraceno (μg/kg)",
    "Acenafteno (μg/kg)",
    "Acenaftileno (μg/kg)",
    "Antraceno (μg/kg)",
    "Fenantreno (μg/kg)",
    "Fluoranteno (μg/kg)",
    "Fluoreno (μg/kg)",
    "2-Metilnaftaleno (μg/kg)",
    "Naftaleno (μg/kg)",
    "Pireno (μg/kg)",
    "Somátoria de HPAs (μg/kg)",
    "Mortalidade (%)",
    "Amônia não ionizada (mg/L)",
    "Toxicidade",
    "pH",
    "OD (mg/L)",
    "Condutividade (mS25/cm)"
];


export type PMMResultadosRow = {
    [coluna: string]: string;
};

export const expectedColumnsPMM = [
    "Ponto",
    "Data",
    "Direção Ondas",
    "Altura(m)",
    "Período(s)",
    "Maré(m)",
    "Direção da Corrente",
    "Intensidade(m / s) da Corrente",
    "Salinidade(PSU)",
    "Temperatura da água(°C)",
    "Turbidez(NTU)",
    "Intensidade(m / s) do Vento",
    "Direção do Vento",
    "Temperatura do ar(°C)",
    "Pressão atmosférica(hPa)",
]


export type RSARowsType = {
    [coluna: string]: string;
};

export const expectedColumnsRSA = [
    "Ponto",
    "Data",
    "Horário",
    "Pressão Sonora",
    "Profundidade da coluna d'água (m)",
    "Estado do Mar (escala Beaufort)",
    "Distância até a costa (Milhas Náuticas)",
    "Distância de obras marítimas ou outras fontes de ruído"
];

export type QARPoluentesResultadosRow = {
    [coluna: string]: string;
};
export const expectedColumnsQARPoluentes = [
    "ponto",
    "data",
    "material_particulado_mp10_ug_m3",
    "material_particulado_mp2_5_ug_m3",
    "dioxido_de_enxofre_so2_ug_m3",
    "dioxido_de_nitrogenio_no2_ug_m3",
    "ozonio_o3_ug_m3",
    "fumaca_ug_m3",
    "monoxido_de_carbono_co_ppm",
    "particulas_totais_em_suspensao_pts_ug_m3",
];


export type QARFumacaResultadosRow = {
    [coluna: string]: string;
};

export const expectedColumnsQARFumaca = [
    "Ponto",
    "Data",
    "Densidade_porcentagem",
    "Tipo_de_Veiculo",
    "Placa",
];


export const expectedColumnsQEF = [
    "ponto",
    "data",
    "tipo_de_analise_ph",
    "temperatura_da_amostra_c",
    "turbidez_ntu",
    "oxigenio_dissolvido_od_mg_l",
    "solidos_sedimentaveis_ml_l",
    "solidos_em_suspensao_totais_mg_l",
    "demanda_bioquimica_de_oxigenio_dbo_20_mg_l",
    "demanda_bioquimica_de_oxigenio_ensaio_05_dias_mg_l",
    "demanda_quimica_de_oxigenio_mg_l",
    "fosforo_total_mg_p_l",
    "nitrogenio_amoniacal_mg_l",
    "nitrogenio_metodo_macro_kjeldahl_mg_l",
    "nitrogenio_organico_mg_l",
    "nitrato_metodo_de_reducao_com_cadmio_mg_l",
    "determinacao_qualitativa_de_materiais_flutuantes",
    "oleos_e_graxas_totais_mg_l",
    "contagem_de_coliformes_termotolerantes_ufc_100ml",
    "arsenio_total_mg_l",
    "bario_total_mg_l",
    "boro_total_mg_l",
    "cadmio_total_mg_l",
    "chumbo_total_mg_l",
    "cianeto_total_mg_l",
    "cianeto_livre_destilavel_por_acidos_fracos_mg_l",
    "cobre_dissolvido_mg_l",
    "cromo_hexavalente_mg_l",
    "cromo_trivalente_mg_l",
    "estanho_total_mg_l",
    "ferro_dissolvido_mg_l",
    "fluoreto_total_mg_l",
    "manganes_dissolvido_mg_l",
    "mercurio_total_mg_l",
    "niquel_total_mg_l",
    "nitrogenio_amoniacal_total_mg_l",
    "prata_total_mg_l",
    "selenio_total_mg_l",
    "sulfeto_mg_l",
    "zinco_total_mg_l",
    "benzeno_mg_l",
    "cloroformio_mg_l",
    "dicloroeteno_somatorio_de_1_1_1_2cis_1_2_trans_mg_l",
    "estireno_mg_l",
    "etilbenzeno_mg_l",
    "fenois_totais_substancias_que_reagem_com_4_aminoantipirina_mg_l",
    "tetracloreto_de_carbono_mg_l",
    "tricloroeteno_mg_l",
    "tolueno_mg_l",
    "xileno_mg_l",
    "materiais_sedimentaveis_ml_l",
    "substancias_soluveis_mg_l",
    "materiais_flutuantes"
];


export type NPSResultadosRow = {
    [coluna: string]: string;
};
export const expectedColumnsNPS = [
    "ponto",
    "data",
    "tipo_de_analise",
    "periodo",
    "vento",
    "condicoes_meteorologicas",
    "limites_de_niveis_de_pressao_sonora_dB",
];

